### ISSUE TITLE
Memory problems with "big" volume

### ISSUE THREAD

**Issue by IamShodan** [pschanely/shrimpdb#1]
Shrimpdb have some problem while working with large datasets.

Error:

> Traceback (most recent call last):
>   File "1.py", line 6, in <module>
>     for x in range(0, 1000000000):
> MemoryError

Code:
```
import shrimpdb
db = shrimpdb.ShrimpDb(filename='test.shrimpdb')
with db as root:
    root['people'] = {'Phillip': {'age':34}, 'Tyler':{'age':5}}

    for x in range(0, 100000000):
        root[x] = [x*2, x*3, x*4]
```

**Comment by pschanely** [comment]
Indeed, for each writing session, you'll need to be able to fit the current set of data in memory. So if you want to write a lot of data at once, you'll need to write it in batches.

Furthermore, for large datasets, you won't want a single big dictionary; instead you'll want to form a tree of dictionaries. Doing this allows you to avoid loading parts of the tree that you aren't using. Finally because it's JSON under the hood, you'll want to use string keys.

Putting all that together, you want to do something more like this:

```python
import shrimpdb
db = shrimpdb.ShrimpDb(filename='test.shrimpdb')

x = 0
for ch1 in map(str,range(100)):
    for ch2 in map(str, range(100)):
        print('writing block', ch1, ch2)
        with db as root:
            items = {}
            for item in map(str, range(0, 100)):
                x += 1
                items[item] = [x*2, x*3, x*4]
            ptr = root.setdefault(ch1, {})
            ptr[ch2] = items
print('Example item:')
print(db.view()['22']['85']['7'])
```

Finally, I guess I should comment that shrimpdb is mostly more of an oddity than anything else; there aren't a ton of use cases that I'd recommend it for. But I do think the project is an interesting case study for: (1) semi-readable plaintext storage formats, and (2) packing a ton of features into a tiny bit of python code. That said, if you do end up using it for something, I'd love to hear about it! Cheers!
